"""empty message

Revision ID: 23529ad70b31
Revises: 5167bd9a6d80
Create Date: 2020-09-10 19:35:17.936055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23529ad70b31'
down_revision = '5167bd9a6d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'suscripcion', 'contact', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'suscripcion', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suscripcion', type_='foreignkey')
    op.drop_constraint(None, 'suscripcion', type_='foreignkey')
    # ### end Alembic commands ###
