"""empty message

Revision ID: ce51f02ec3a3
Revises: a824c856db92
Create Date: 2020-09-10 16:01:36.673545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce51f02ec3a3'
down_revision = 'a824c856db92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'suscripcion', 'group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'suscripcion', 'contact', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suscripcion', type_='foreignkey')
    op.drop_constraint(None, 'suscripcion', type_='foreignkey')
    # ### end Alembic commands ###
