"""empty message

Revision ID: d0c214572f97
Revises: 23529ad70b31
Create Date: 2020-09-10 20:47:52.748383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c214572f97'
down_revision = '23529ad70b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'suscripcion', 'contact', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'suscripcion', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suscripcion', type_='foreignkey')
    op.drop_constraint(None, 'suscripcion', type_='foreignkey')
    # ### end Alembic commands ###
